import subprocess
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

# data generated by https://github.com/jdh4/saccta/blob/main/rc_users_by_year.sh
years = range(2017, 2024)
users = [666, 781, 931, 1080, 1272, 1385, 1603]
users_plus_adroit = [882, 1202, 1373, 1573, 1788, 1930, 2318]
cpu_hours = [168149984, 237840674, 272273203, 304113195, 398226937, 502300526, 461457485]
gpu_hours = [937572, 1983304, 2594004, 3364813, 3572016, 3722861, 3818634]

nrows = 1
ncols = 3

opts = {"mfc":"tab:blue",
        "mec":"tab:blue",
        "linestyle":'dashed',
        "linewidth":1,
        "markersize":6,
        "color":'lightgrey'}
opts2 = {"mfc":"tab:red",
         "mec":"tab:red",
         "linestyle":'dashed',
         "linewidth":1,
         "markersize":6,
         "color":'lightgrey'}

fig = plt.figure(figsize=(12, 2.5))
plt.subplot(nrows, ncols, 1)
plt.plot(years, users, 'o', label="Large Clusters", **opts)
plt.plot(years, users_plus_adroit, 'o', label="Large Clusters Plus Adroit", **opts2)
plt.xlabel("Year")
plt.ylabel("Number of Users")
plt.xticks(years, map(str, years))
#plt.ylim(500, 3000)
plt.legend(fontsize="8")

plt.subplot(nrows, ncols, 2)
plt.plot(years, [x/1e6 for x in cpu_hours], 'o', **opts)
plt.xlabel("Year")
plt.ylabel("CPU-Hours / $10^6$")
plt.xticks(years, map(str, years))

plt.subplot(nrows, ncols, 3)
plt.plot(years, [x/1e6 for x in gpu_hours], 'o', **opts)
plt.xlabel("Year")
plt.ylabel("GPU-Hours / $10^6$")
plt.xticks(years, map(str, years))

plt.tight_layout()
cluster = "overall_users_and_xpu_hours"
plt.savefig(f"{cluster}_history.png", dpi=200)
plt.savefig(f"{cluster}_history.pdf")
