import subprocess
import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pyplot as plt

# data generated by https://github.com/jdh4/saccta/blob/main/rc_users_by_year.sh
# sacct -M adroit -a -X -P -n -S 2025-01-01T00:00:00 -E 2025-12-31T23:59:59 -o user | sort | uniq > adroit.2025

years = range(2017, 2026)
users = [666, 781, 931, 1080, 1272, 1385, 1603, 1914, 2200]
users_plus_adroit = [882, 1202, 1373, 1573, 1788, 1930, 2318, 2922, 3380]
cpu_hours = [168149984, 237840674, 272273203, 304113195, 398226937, 502300526, 461457485, 513591447, 770416957]
gpu_hours = [937572, 1983304, 2594004, 3364813, 3572016, 3722861, 3818634, 5617785, 5983260]

years_sp = range(2019, 2026)
sponsors = [217, 250, 264, 268, 277, 318, 343]

nrows = 2
ncols = 2

opts = {"mfc":"tab:blue",
        "mec":"tab:blue",
        "linestyle":'dashed',
        "linewidth":1,
        "markersize":8,
        "color":'lightgrey'}
opts2 = {"mfc":"tab:red",
         "mec":"tab:red",
         "linestyle":'dashed',
         "linewidth":1,
         "markersize":8,
         "color":'lightgrey'}

mpl.rcParams['axes.labelsize'] = 16
mpl.rcParams['axes.titlesize'] = 20
mpl.rcParams['xtick.labelsize'] = 12
mpl.rcParams['ytick.labelsize'] = 12

fig = plt.figure(figsize=(12, 8))
plt.subplot(nrows, ncols, 1)
plt.plot(years, users, 'o', label="Large Clusters", **opts)
plt.plot(years, users_plus_adroit, 'o', label="Large Clusters Plus Adroit", **opts2)
plt.xlabel("Year")
plt.ylabel("Number of Users")
plt.xticks(years, map(str, years))
#plt.ylim(500, 3000)
plt.legend(fontsize="12")

plt.subplot(nrows, ncols, 2)
plt.plot(years_sp, sponsors, 'o', **opts)
plt.xlabel("Year")
plt.ylabel("Number of Sponsors")
plt.xlim(2016.6, 2025.4)
plt.xticks(years, map(str, years))

plt.subplot(nrows, ncols, 3)
plt.plot(years, [x/1e6 for x in cpu_hours], 'o', **opts)
plt.xlabel("Year")
plt.ylabel("CPU-Hours / $10^6$")
plt.xticks(years, map(str, years))

plt.subplot(nrows, ncols, 4)
plt.plot(years, [x/1e6 for x in gpu_hours], 'o', **opts)
plt.xlabel("Year")
plt.ylabel("GPU-Hours / $10^6$")
plt.xticks(years, map(str, years))

plt.tight_layout(pad=2, h_pad=4, w_pad=4)
cluster = "overall_users_and_xpu_hours"
plt.savefig(f"{cluster}_history.png", dpi=200)
plt.savefig(f"{cluster}_history.pdf")
