import sponsor

def main():
    # input file is generated by https://github.com/jdh4/saccta/blob/main/rc_users_by_year.sh
    with open("large_cluster_users_2022", "r") as fo:
        lines = fo.readlines()
    netids = [line.strip() for line in lines]
    netids = sorted(set(netids))
    print(netids)
    print(len(netids))

    sponsors = []
    for netid in netids:
        d = sponsor.get_sponsor_netid_per_cluster_dict_from_ldap(netid, verbose=True, strip=False)
        d.pop("displayname")
        if len(set(d.values())) != 1: print(f"W: {netid} has multiple sponsors.", flush=True)
        # della is an arbitrary choice in next line
        if d["della"]:
            sponsors.append(d["della"])
    print(sorted(set(sponsors)))
    print(len(set(sponsors)))


if __name__ == "__main__":
    main()
